### ISSUE TITLE
STM32F0 need various other bits in board.h

### ISSUE THREAD

**Issue by adamgreig** [HarkonenBade/gen-board.h#1]
Specifically it looks like we want a
`#define STM32_LSEDRV                (3U << 3U)`
and
`#define STM32_HSE_BYPASS`
but no sign of
`#define STM32_VDD 330`

Maybe worth going via the mcus file or something?

**Comment by HarkonenBade** [comment]
Are both of the firs two fixed for all STM32F0 boards? Or do they have potentially variable values (i.e. is the 3U << 3U fixed?).

Yeah, I might break out a 'global values' per MCU

**Comment by adamgreig** [comment]
They're something you might want to set depending on your application, irregardless of your choice of STM32F0, as I understand it.

**Comment by HarkonenBade** [comment]
Ok, Just pondering if a more general bit for throwing in application specific defines is needed, or an MCU specific one. It is sounding like this is more a general problem than one of some values specific to the F0.

**Comment by adamgreig** [comment]
Yep agreed. Perhaps best would be a way of setting any number of defines to whatever you want, and that can then include the clock frequencies you already do. Maybe then give a few "template" yaml files for each family of microcontrollers to make it easier for people to get started with the right things.

**Comment by HarkonenBade** [comment]
Based on the latest example board.h files in the ChibiOS repos I am unsure as to if this is still an issue?

**Comment by danielsaul** [comment]
This is still an issue, for the L0 I've got
```
#define STM32_LSEDRV                (3U << 11U)
#define STM32_HSE_BYPASS
```
which currently I've added manually to my board.h
May look at adding support for custom defines myself sometime.
