### ISSUE TITLE
F4 with ethernet needs some extra fields

### ISSUE THREAD

**Issue by cillian64** [HarkonenBade/gen-board.h#3]
board.h for an f4 with ethernet in use includes at minimum:

```
/*
    Ethernet related stuff
*/
#define BOARD_PHY_ID                    0x00221560
#define BOARD_PHY_RMII
```

I believe you can define a BOARD_PHY_ADDRESS or a BOARD_PHY_ID which is then used to find the address.  BOARD_PHY_RMII is defined, or not defined if you're using MII instead of RMII. There are various other BOARD_PHY options in `ChibiOS/os/hal/ports/STM32/LLD/MACv1/hal_mac_lld.c`

**Comment by HarkonenBade** [comment]
Peripheral setup has been deemed beyond the scope of this project.
